# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "centos/7"
  config.vm.network "private_network", ip: "192.168.56.12"
  config.vm.hostname = "azure-wso2"
  config.hostmanager.enabled = true
  config.hostmanager.ignore_private_ip = false
  config.vm.synced_folder "ansible-apim/", "/home/vagrant/ansible-apim"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "4096"
    vb.cpus = 2
    vb.name = "azure-wso2"
  end
  #config.vm.provision :shell, path: "./scripts/init.sh"
  #config.vm.provision "ansible" do |ansible|
  #  ansible.playbook = "ansible-apim/site.yml"
  #  ansible.inventory_path = "ansible-apim/dev"
  #  ansible.limit = 'all'
  #end
end
